framework:
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true
        storage_factory_id: session.storage.factory.native
    default_locale: 'pl'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['pl']
