framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
 
        routing:
            'App\Message\GenerateEmployeeReportMessage': async
            'App\Message\GenerateDepartmentReportMessage': async